apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yc-billing-exporter.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "yc-billing-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "yc-billing-exporter.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "yc-billing-exporter.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: TOKEN
            - name: YCBILLINGID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: YCBILLINGID
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
