apiVersion: v1
kind: Service
metadata:
  name: {{ include "yc-billing-exporter.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "yc-billing-exporter.selectorLabels" . | nindent 4 }}
